Preview 1.9.5
aliyun/aliyun-oss-go-sdk pull request #150
Opened 2019-02-15 03:12 UTC by wangtaowei

add speed limit upload

2019-02-18 12:09 UTC, coderall commented on .travis.yml
> +- if [[ $TRAVIS_GO_VERSION == '1.8' ]]; then go get golang.org/x/time/rate ; fi
这两行if的逻辑一样

2019-02-18 12:10 UTC, coderall commented on oss/band_limit_reader.go
> +package oss
文件名中的band是指？

2019-02-18 12:10 UTC, coderall commented on oss/band_limit_reader.go
> +package oss
bandwidth？

2019-02-18 12:13 UTC, coderall commented on oss/conf.go
> +		return fmt.Errorf("erro,speed is less than 0")
缩进

2019-02-18 12:14 UTC, coderall commented on oss/conf.go
> +		config.UploadLimitSpeed = 0
同上

2019-02-18 12:14 UTC, coderall commented on oss/conf.go
> +		config.UploadLimitSpeed = 0
同时，这里的speed==0的逻辑是否等同于禁止上传操作

2019-02-18 12:21 UTC, coderall commented on oss/conn.go
> +		if req.ContentLength > 0 {
为什么要加contentlength的判断？

2019-02-18 12:25 UTC, coderall commented on oss/band_limit_reader.go
> +	var end int
建议使用64位变量

2019-02-18 12:28 UTC, coderall commented on oss/band_limit_reader.go
> +			err = fmt.Errorf("ReserveN error,start:%d,end:%d,burst:%d,perTokenBandSize:%d",
log内容不是很直观

2019-02-18 12:31 UTC, coderall commented on oss/band_limit_reader.go
> +			return
不return 一个 error？

2019-02-18 12:34 UTC, coderall commented on oss/bucket_test.go
> +	return
这里漏了 return upSpeed？

2019-02-18 12:36 UTC, coderall commented on oss/client_test.go
> +	// compare with go1.7
这里好像没看到具体的判断上传速度的逻辑？

2019-02-18 12:42 UTC, coderall commented on oss/conf.go
> +	UploadLimitSpeed int          // Upload limit speed:KB/s, 0 is unlimited
如果可以的话，建议在后面追加，这样diff 文件看起来方便点

2019-02-19 08:57 UTC, wangtaowei commented on .travis.yml
> +- if [[ $TRAVIS_GO_VERSION == '1.8' ]]; then go get golang.org/x/time/rate ; fi
按照建议修改，使用 shell中的>=逻辑

2019-02-19 08:58 UTC, wangtaowei commented on oss/band_limit_reader.go
> +package oss
按照建议修改，使用完整的英文单词bandwidth

2019-02-19 09:04 UTC, wangtaowei commented on oss/conf.go
> +		return fmt.Errorf("erro,speed is less than 0")
在vi以及notepad工具都是对齐的，这里可能是页面的问题

2019-02-19 09:05 UTC, wangtaowei commented on oss/conf.go
> +		config.UploadLimitSpeed = 0
为0表示不限速，go中struct的默认值都是0

2019-02-19 09:06 UTC, wangtaowei commented on oss/conn.go
> +		if req.ContentLength > 0 {
限速只对body中的数据限速，不会对整个http协议包进行限速，所以加了一个对contentlength的判断

2019-02-19 09:06 UTC, wangtaowei commented on oss/band_limit_reader.go
> +	var end int
因为go的Read接口返回值定义为int类型，所以这里只能用int类型

2019-02-19 09:07 UTC, wangtaowei commented on oss/band_limit_reader.go
> +			err = fmt.Errorf("ReserveN error,start:%d,end:%d,burst:%d,perTokenBandSize:%d",
按照建议修改，在错误信息中增加struct名字和函数名字

2019-02-19 09:08 UTC, wangtaowei commented on oss/band_limit_reader.go
> +			return
这是由go的语法支持的，error之前逻辑已经赋值了，这里可以直接return

2019-02-19 09:09 UTC, wangtaowei commented on oss/bucket_test.go
> +	return
这是由go的语法支持的，upSpeed已经赋值了，这里可以直接return

2019-02-19 09:10 UTC, wangtaowei commented on oss/client_test.go
> +	// compare with go1.7
把函数名改为TestSetLimitUploadSpeed就不会有歧义了，这里仅表示测试设置参数是否能成功

2019-02-19 09:11 UTC, wangtaowei commented on oss/conf.go
> +	UploadLimitSpeed int          // Upload limit speed:KB/s, 0 is unlimited
按照建议修改

2019-02-20 02:16 UTC, FunriLy requested changes

2019-02-20 02:16 UTC, FunriLy commented on oss/band_limit_reader.go
> +	limiter := rate.NewLimiter(rate.Limit(bandSpeed), bandSpeed)
Limiter的两个参数，第一个参数为允许每秒发生多少次事件，第二个参数是其缓存最大可存多少个事件。
通常情况下，容量设置应该大于当前最高并行量为好。

2019-02-20 02:16 UTC, FunriLy commented on oss/conf.go
> +		return fmt.Errorf("erro,speed is less than 0")
不要使用Tab键，修改IDE设置，设置tab为4个空格

2019-02-20 03:19 UTC, wangtaowei commented on oss/band_limit_reader.go
> +	limiter := rate.NewLimiter(rate.Limit(bandSpeed), bandSpeed)
一般情况下，两个参数设置的为相等比较好

2019-02-20 04:51 UTC, wangtaowei commented on oss/conf.go
> +		return fmt.Errorf("erro,speed is less than 0")
go的对齐是插件工具做的，默认用tab键，修改ide设置无效，还没有找到用空格键代替tab键格式化的设置方法。

2019-02-28 08:28 UTC, hangzws commented on oss/conf.go
> +		return fmt.Errorf("erro,speed is less than 0")
这个地方统一使用vscode就好了

2019-02-28 08:28 UTC, hangzws commented on oss/conf.go
> +	UploadLimitSpeed int          // Upload limit speed:KB/s, 0 is unlimited
只做了上传限速么？下载呢？

2019-02-28 08:28 UTC, hangzws commented on oss/bucket_test.go
> +	return
最好用标准的语法

2019-02-28 08:28 UTC, hangzws commented on oss/conn.go
> +		if req.ContentLength > 0 {
上传同一个对象的话，如果是多个routine，每一个routine里有一个request怎么解决？

2019-02-28 08:28 UTC, hangzws commented on oss/bucket_test.go
> +	archiveBucketName := bucketName + "-archive"
这个地方为啥要这样改？

2019-02-28 08:28 UTC, hangzws commented on oss/client_test.go
> +	bucketName        = "go-sdk-test-bucket-abcx-for-object" + randLowStr(5)
这个后面安排统一改

2019-03-04 01:40 UTC, wangtaowei commented on oss/conf.go
> +		return fmt.Errorf("erro,speed is less than 0")
这里用的就是vscode

2019-03-04 01:46 UTC, wangtaowei commented on oss/conn.go
> +		if req.ContentLength > 0 {
限速参数是和一个client实例对应的，多个routin中有多个request，每个request的method都是一样的，所以都会走到限速逻辑

2019-03-04 01:49 UTC, wangtaowei commented on oss/bucket_test.go
> +	return
这里按照建议修改

2019-03-04 01:51 UTC, wangtaowei commented on oss/conf.go
> +	UploadLimitSpeed int          // Upload limit speed:KB/s, 0 is unlimited
下载一般不限速

2019-03-04 01:53 UTC, wangtaowei commented on oss/client_test.go
> +	bucketName        = "go-sdk-test-bucket-abcx-for-object" + randLowStr(5)
按照讨论结果，后续单独版本统一改

2019-03-04 02:04 UTC, wangtaowei commented on oss/bucket_test.go
> +	archiveBucketName := bucketName + "-archive"
这里改回去，用统一全局变量

2019-03-05 13:10 UTC, merged